// <auto-generated />
using DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Main.Migrations
{
    [DbContext(typeof(MiDbContext))]
    [Migration("20241015043838_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataBase.Table.PersonaTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Perez",
                            Correo = "juancarlos.perez@example.com",
                            Edad = 35,
                            Nombre = "Juan Carlos",
                            Telefono = 998765432,
                            estado = true
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Garcia",
                            Correo = "marialuisa.garcia@example.com",
                            Edad = 28,
                            Nombre = "Maria Luisa",
                            Telefono = 975342189,
                            estado = true
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Sánchez",
                            Correo = "carlos.sanchez@example.com",
                            Edad = 42,
                            Nombre = "Carlos Alberto",
                            Telefono = 964567321,
                            estado = true
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "Rojas",
                            Correo = "ana.rojas@example.com",
                            Edad = 30,
                            Nombre = "Ana Beatriz",
                            Telefono = 953245678,
                            estado = true
                        },
                        new
                        {
                            Id = 5,
                            Apellido = "Flores",
                            Correo = "pedro.flores@example.com",
                            Edad = 50,
                            Nombre = "Pedro Enrique",
                            Telefono = 987654321,
                            estado = true
                        },
                        new
                        {
                            Id = 6,
                            Apellido = "Torres",
                            Correo = "lucia.torres@example.com",
                            Edad = 22,
                            Nombre = "Lucia Fernanda",
                            Telefono = 912345678,
                            estado = true
                        },
                        new
                        {
                            Id = 7,
                            Apellido = "Mendoza",
                            Correo = "raul.mendoza@example.com",
                            Edad = 40,
                            Nombre = "Raul Andres",
                            Telefono = 934567890,
                            estado = true
                        },
                        new
                        {
                            Id = 8,
                            Apellido = "Quispe",
                            Correo = "gabriela.quispe@example.com",
                            Edad = 29,
                            Nombre = "Gabriela Patricia",
                            Telefono = 923456789,
                            estado = true
                        },
                        new
                        {
                            Id = 9,
                            Apellido = "Chávez",
                            Correo = "fernando.chavez@example.com",
                            Edad = 34,
                            Nombre = "Fernando",
                            Telefono = 921345678,
                            estado = true
                        },
                        new
                        {
                            Id = 10,
                            Apellido = "Vargas",
                            Correo = "isabel.vargas@example.com",
                            Edad = 27,
                            Nombre = "Isabel Cristina",
                            Telefono = 918765432,
                            estado = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
